spring:
  application:
    name: santander-dev-week-2024-Andrehlb
  datasource:
    url: jdbc:h2:mem:sdw2024-Andrehlb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true